//
//  Activity.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - Activity properties

extension Activity {

    @NSManaged var actDescription: String?
    @NSManaged var activityID: String?
    @NSManaged var createdAt: NSDate?
    @NSManaged var endAt: NSDate?
    @NSManaged var location_des: String?
    @NSManaged var location_x: Double // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var location_y: Double // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var maxAttend: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var name: String?
    @NSManaged var poster: String?
    @NSManaged var startAt: NSDate?

    @NSManaged var club: Club?
    @NSManaged var user: User?

}

// MARK: - Activity query attributes

extension Activity {

    static let actDescription = AlecrimCoreData.NullableAttribute<String>("actDescription")
    static let activityID = AlecrimCoreData.NullableAttribute<String>("activityID")
    static let createdAt = AlecrimCoreData.NullableAttribute<NSDate>("createdAt")
    static let endAt = AlecrimCoreData.NullableAttribute<NSDate>("endAt")
    static let location_des = AlecrimCoreData.NullableAttribute<String>("location_des")
    static let location_x = AlecrimCoreData.NullableAttribute<Double>("location_x")
    static let location_y = AlecrimCoreData.NullableAttribute<Double>("location_y")
    static let maxAttend = AlecrimCoreData.NullableAttribute<Int32>("maxAttend")
    static let name = AlecrimCoreData.NullableAttribute<String>("name")
    static let poster = AlecrimCoreData.NullableAttribute<String>("poster")
    static let startAt = AlecrimCoreData.NullableAttribute<NSDate>("startAt")

    static let club = AlecrimCoreData.NullableAttribute<Club>("club")
    static let user = AlecrimCoreData.NullableAttribute<User>("user")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: Activity {

    var actDescription: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("actDescription", self) }
    var activityID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("activityID", self) }
    var createdAt: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("createdAt", self) }
    var endAt: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("endAt", self) }
    var location_des: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("location_des", self) }
    var location_x: AlecrimCoreData.NullableAttribute<Double> { return AlecrimCoreData.NullableAttribute<Double>("location_x", self) }
    var location_y: AlecrimCoreData.NullableAttribute<Double> { return AlecrimCoreData.NullableAttribute<Double>("location_y", self) }
    var maxAttend: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("maxAttend", self) }
    var name: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("name", self) }
    var poster: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("poster", self) }
    var startAt: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("startAt", self) }

    var club: AlecrimCoreData.NullableAttribute<Club> { return AlecrimCoreData.NullableAttribute<Club>("club", self) }
    var user: AlecrimCoreData.NullableAttribute<User> { return AlecrimCoreData.NullableAttribute<User>("user", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var activities: AlecrimCoreData.Table<Activity> { return AlecrimCoreData.Table<Activity>(dataContext: self) }

}

