//
//  ChatRecord.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - ChatRecord properties

extension ChatRecord {

    @NSManaged var audio: String?
    @NSManaged var chat_type: String?
    @NSManaged var createdAt: NSDate?
    @NSManaged var hidden: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var image: String?
    @NSManaged var messageType: String?
    @NSManaged var recordID: String?
    @NSManaged var relatedID: String?
    @NSManaged var sent: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var targetID: String?
    @NSManaged var textContent: String?

    @NSManaged var sender: User?

}

// MARK: - ChatRecord query attributes

extension ChatRecord {

    static let audio = AlecrimCoreData.NullableAttribute<String>("audio")
    static let chat_type = AlecrimCoreData.NullableAttribute<String>("chat_type")
    static let createdAt = AlecrimCoreData.NullableAttribute<NSDate>("createdAt")
    static let hidden = AlecrimCoreData.NullableAttribute<Bool>("hidden")
    static let image = AlecrimCoreData.NullableAttribute<String>("image")
    static let messageType = AlecrimCoreData.NullableAttribute<String>("messageType")
    static let recordID = AlecrimCoreData.NullableAttribute<String>("recordID")
    static let relatedID = AlecrimCoreData.NullableAttribute<String>("relatedID")
    static let sent = AlecrimCoreData.NullableAttribute<Bool>("sent")
    static let targetID = AlecrimCoreData.NullableAttribute<String>("targetID")
    static let textContent = AlecrimCoreData.NullableAttribute<String>("textContent")

    static let sender = AlecrimCoreData.NullableAttribute<User>("sender")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: ChatRecord {

    var audio: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("audio", self) }
    var chat_type: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("chat_type", self) }
    var createdAt: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("createdAt", self) }
    var hidden: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("hidden", self) }
    var image: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("image", self) }
    var messageType: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("messageType", self) }
    var recordID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("recordID", self) }
    var relatedID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("relatedID", self) }
    var sent: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("sent", self) }
    var targetID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("targetID", self) }
    var textContent: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("textContent", self) }

    var sender: AlecrimCoreData.NullableAttribute<User> { return AlecrimCoreData.NullableAttribute<User>("sender", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var chatRecords: AlecrimCoreData.Table<ChatRecord> { return AlecrimCoreData.Table<ChatRecord>(dataContext: self) }

}

