//
//  Club.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - Club properties

extension Club {

    @NSManaged var clubDescription: String?
    @NSManaged var clubID: String?
    @NSManaged var created_at: NSDate?
    @NSManaged var logo_url: String?
    @NSManaged var name: String?

    @NSManaged var host: User?
    @NSManaged var mostRecentChat: ChatRecord?

    @NSManaged var members: Set<User>

}

// MARK: - Club KVC compliant to-many accessors and helpers

extension Club {

    @NSManaged private func addMembersObject(object: User)
    @NSManaged private func removeMembersObject(object: User)
    @NSManaged func addMembers(members: Set<User>)
    @NSManaged func removeMembers(members: Set<User>)

    func addMember(member: User) { self.addMembersObject(member) }
    func removeMember(member: User) { self.removeMembersObject(member) }

}

// MARK: - Club query attributes

extension Club {

    static let clubDescription = AlecrimCoreData.NullableAttribute<String>("clubDescription")
    static let clubID = AlecrimCoreData.NullableAttribute<String>("clubID")
    static let created_at = AlecrimCoreData.NullableAttribute<NSDate>("created_at")
    static let logo_url = AlecrimCoreData.NullableAttribute<String>("logo_url")
    static let name = AlecrimCoreData.NullableAttribute<String>("name")

    static let host = AlecrimCoreData.NullableAttribute<User>("host")
    static let mostRecentChat = AlecrimCoreData.NullableAttribute<ChatRecord>("mostRecentChat")

    static let members = AlecrimCoreData.Attribute<Set<User>>("members")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: Club {

    var clubDescription: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("clubDescription", self) }
    var clubID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("clubID", self) }
    var created_at: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("created_at", self) }
    var logo_url: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("logo_url", self) }
    var name: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("name", self) }

    var host: AlecrimCoreData.NullableAttribute<User> { return AlecrimCoreData.NullableAttribute<User>("host", self) }
    var mostRecentChat: AlecrimCoreData.NullableAttribute<ChatRecord> { return AlecrimCoreData.NullableAttribute<ChatRecord>("mostRecentChat", self) }

    var members: AlecrimCoreData.Attribute<Set<User>> { return AlecrimCoreData.Attribute<Set<User>>("members", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var clubs: AlecrimCoreData.Table<Club> { return AlecrimCoreData.Table<Club>(dataContext: self) }

}

