//
//  NewsComment.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - NewsComment properties

extension NewsComment {

    @NSManaged var commentID: String?
    @NSManaged var content: String?
    @NSManaged var createdAt: NSDate?
    @NSManaged var image: String?

    @NSManaged var news: News?
    @NSManaged var user: User?

}

// MARK: - NewsComment query attributes

extension NewsComment {

    static let commentID = AlecrimCoreData.NullableAttribute<String>("commentID")
    static let content = AlecrimCoreData.NullableAttribute<String>("content")
    static let createdAt = AlecrimCoreData.NullableAttribute<NSDate>("createdAt")
    static let image = AlecrimCoreData.NullableAttribute<String>("image")

    static let news = AlecrimCoreData.NullableAttribute<News>("news")
    static let user = AlecrimCoreData.NullableAttribute<User>("user")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: NewsComment {

    var commentID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("commentID", self) }
    var content: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("content", self) }
    var createdAt: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("createdAt", self) }
    var image: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("image", self) }

    var news: AlecrimCoreData.NullableAttribute<News> { return AlecrimCoreData.NullableAttribute<News>("news", self) }
    var user: AlecrimCoreData.NullableAttribute<User> { return AlecrimCoreData.NullableAttribute<User>("user", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var newsComments: AlecrimCoreData.Table<NewsComment> { return AlecrimCoreData.Table<NewsComment>(dataContext: self) }

}

