//
//  Profile.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - Profile properties

extension Profile {

    @NSManaged var avatarCarID: String?
    @NSManaged var avatarCarImage: String?
    @NSManaged var avatarClubID: String?
    @NSManaged var avatarClubLogo: String?
    @NSManaged var fansNum: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var followNum: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var statusNum: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var avatarClubName: String?
    @NSManaged var avatarCarName: String?
    @NSManaged var avatarCarLogo: String?

    @NSManaged var user: User?

}

// MARK: - Profile query attributes

extension Profile {

    static let avatarCarID = AlecrimCoreData.NullableAttribute<String>("avatarCarID")
    static let avatarCarImage = AlecrimCoreData.NullableAttribute<String>("avatarCarImage")
    static let avatarClubID = AlecrimCoreData.NullableAttribute<String>("avatarClubID")
    static let avatarClubLogo = AlecrimCoreData.NullableAttribute<String>("avatarClubLogo")
    static let fansNum = AlecrimCoreData.NullableAttribute<Int32>("fansNum")
    static let followNum = AlecrimCoreData.NullableAttribute<Int32>("followNum")
    static let statusNum = AlecrimCoreData.NullableAttribute<Int32>("statusNum")
    static let avatarClubName = AlecrimCoreData.NullableAttribute<String>("avatarClubName")
    static let avatarCarName = AlecrimCoreData.NullableAttribute<String>("avatarClubName")
    static let avatarCarLogo = AlecrimCoreData.NullableAttribute<String>("avatarCarLogo")
    static let user = AlecrimCoreData.NullableAttribute<User>("user")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: Profile {

    var avatarCarID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("avatarCarID", self) }
    var avatarCarImage: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("avatarCarImage", self) }
    var avatarClubID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("avatarClubID", self) }
    var avatarClubLogo: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("avatarClubLogo", self) }
    var fansNum: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("fansNum", self) }
    var followNum: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("followNum", self) }
    var statusNum: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("statusNum", self) }
    var avatarClubName: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("avatarClubName", self) }
    var avatarCarName: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("avatarCarName", self) }
    var avatarCarLogo: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("avatarCarLogo", self) }
    var user: AlecrimCoreData.NullableAttribute<User> { return AlecrimCoreData.NullableAttribute<User>("user", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var profiles: AlecrimCoreData.Table<Profile> { return AlecrimCoreData.Table<Profile>(dataContext: self) }

}

