//
//  SportCar.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - SportCar properties

extension SportCar {

    @NSManaged var body: String?
    @NSManaged var engine: String?
    @NSManaged var identified: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var image: String?
    @NSManaged var logo: String?
    @NSManaged var manufacturer: String?
    @NSManaged var maxSpeed: String?
    @NSManaged var mine: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var name: String?
    @NSManaged var price: String?
    @NSManaged var signature: String?
    @NSManaged var torque: String?
    @NSManaged var zeroTo60: String?

}

// MARK: - SportCar query attributes

extension SportCar {

    static let body = AlecrimCoreData.NullableAttribute<String>("body")
    static let engine = AlecrimCoreData.NullableAttribute<String>("engine")
    static let identified = AlecrimCoreData.NullableAttribute<Bool>("identified")
    static let image = AlecrimCoreData.NullableAttribute<String>("image")
    static let logo = AlecrimCoreData.NullableAttribute<String>("logo")
    static let manufacturer = AlecrimCoreData.NullableAttribute<String>("manufacturer")
    static let maxSpeed = AlecrimCoreData.NullableAttribute<String>("maxSpeed")
    static let mine = AlecrimCoreData.NullableAttribute<Bool>("mine")
    static let name = AlecrimCoreData.NullableAttribute<String>("name")
    static let price = AlecrimCoreData.NullableAttribute<String>("price")
    static let signature = AlecrimCoreData.NullableAttribute<String>("signature")
    static let torque = AlecrimCoreData.NullableAttribute<String>("torque")
    static let zeroTo60 = AlecrimCoreData.NullableAttribute<String>("zeroTo60")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: SportCar {

    var body: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("body", self) }
    var engine: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("engine", self) }
    var identified: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("identified", self) }
    var image: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("image", self) }
    var logo: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("logo", self) }
    var manufacturer: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("manufacturer", self) }
    var maxSpeed: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("maxSpeed", self) }
    var mine: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("mine", self) }
    var name: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("name", self) }
    var price: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("price", self) }
    var signature: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("signature", self) }
    var torque: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("torque", self) }
    var zeroTo60: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("zeroTo60", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var sportCars: AlecrimCoreData.Table<SportCar> { return AlecrimCoreData.Table<SportCar>(dataContext: self) }

}

