//
//  BaseModel.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - BaseModel properties

extension BaseModel {

    @NSManaged var hostSSID: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var ssid: Int32 // cannot mark as optional because Objective-C compatibility issues

}

// MARK: - BaseModel query attributes

extension BaseModel {

    static let hostSSID = AlecrimCoreData.NullableAttribute<Int32>("hostSSID")
    static let ssid = AlecrimCoreData.NullableAttribute<Int32>("ssid")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeProtocol where Self.ValueType: BaseModel {

    var hostSSID: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("hostSSID", self) }
    var ssid: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("ssid", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var baseModels: AlecrimCoreData.Table<BaseModel> { return AlecrimCoreData.Table<BaseModel>(dataContext: self) }

}

