//
//  Club.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - Club properties

extension Club {

    @NSManaged var alwayOnTop: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var alwaysOnTopDate: Date?
    @NSManaged var attended: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var city: String?
    @NSManaged var clubDescription: String?
    @NSManaged var createdAt: Date?
    @NSManaged var founder: String?
    @NSManaged var identified: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var logo: String?
    @NSManaged var memberNum: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var mine: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var mostRecentChat: String?
    @NSManaged var name: String?
    @NSManaged var noDisturbing: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var onlyHostCanInvite: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var remarkName: String?
    @NSManaged var showMembers: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var showNickName: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var value: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var valueAverage: Int32 // cannot mark as optional because Objective-C compatibility issues

}

// MARK: - Club query attributes

extension Club {

    static let alwayOnTop = AlecrimCoreData.NullableAttribute<Bool>("alwayOnTop")
    static let alwaysOnTopDate = AlecrimCoreData.NullableAttribute<NSDate>("alwaysOnTopDate")
    static let attended = AlecrimCoreData.NullableAttribute<Bool>("attended")
    static let city = AlecrimCoreData.NullableAttribute<String>("city")
    static let clubDescription = AlecrimCoreData.NullableAttribute<String>("clubDescription")
    static let createdAt = AlecrimCoreData.NullableAttribute<NSDate>("createdAt")
    static let founder = AlecrimCoreData.NullableAttribute<String>("founder")
    static let identified = AlecrimCoreData.NullableAttribute<Bool>("identified")
    static let logo = AlecrimCoreData.NullableAttribute<String>("logo")
    static let memberNum = AlecrimCoreData.NullableAttribute<Int32>("memberNum")
    static let mine = AlecrimCoreData.NullableAttribute<Bool>("mine")
    static let mostRecentChat = AlecrimCoreData.NullableAttribute<String>("mostRecentChat")
    static let name = AlecrimCoreData.NullableAttribute<String>("name")
    static let noDisturbing = AlecrimCoreData.NullableAttribute<Bool>("noDisturbing")
    static let onlyHostCanInvite = AlecrimCoreData.NullableAttribute<Bool>("onlyHostCanInvite")
    static let remarkName = AlecrimCoreData.NullableAttribute<String>("remarkName")
    static let showMembers = AlecrimCoreData.NullableAttribute<Bool>("showMembers")
    static let showNickName = AlecrimCoreData.NullableAttribute<Bool>("showNickName")
    static let value = AlecrimCoreData.NullableAttribute<Int32>("value")
    static let valueAverage = AlecrimCoreData.NullableAttribute<Int32>("valueAverage")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeProtocol where Self.ValueType: Club {

    var alwayOnTop: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("alwayOnTop", self) }
    var alwaysOnTopDate: AlecrimCoreData.NullableAttribute<Date> { return AlecrimCoreData.NullableAttribute<NSDate>("alwaysOnTopDate", self) }
    var attended: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("attended", self) }
    var city: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("city", self) }
    var clubDescription: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("clubDescription", self) }
    var createdAt: AlecrimCoreData.NullableAttribute<Date> { return AlecrimCoreData.NullableAttribute<NSDate>("createdAt", self) }
    var founder: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("founder", self) }
    var identified: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("identified", self) }
    var logo: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("logo", self) }
    var memberNum: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("memberNum", self) }
    var mine: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("mine", self) }
    var mostRecentChat: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("mostRecentChat", self) }
    var name: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("name", self) }
    var noDisturbing: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("noDisturbing", self) }
    var onlyHostCanInvite: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("onlyHostCanInvite", self) }
    var remarkName: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("remarkName", self) }
    var showMembers: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("showMembers", self) }
    var showNickName: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("showNickName", self) }
    var value: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("value", self) }
    var valueAverage: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("valueAverage", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var clubs: AlecrimCoreData.Table<Club> { return AlecrimCoreData.Table<Club>(dataContext: self) }

}

