//
//  RosterItem.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - RosterItem properties

extension RosterItem {

    @NSManaged var alwaysOnTop: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var createdAt: Date?
    @NSManaged var entityData: Data?
    @NSManaged var entityType: String?
    @NSManaged var noDisturbing: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var recentChatDes: String?
    @NSManaged var relatedID: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var unreadNum: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var updatedAt: Date?

}

// MARK: - RosterItem query attributes

extension RosterItem {

    static let alwaysOnTop = AlecrimCoreData.NullableAttribute<Bool>("alwaysOnTop")
    static let createdAt = AlecrimCoreData.NullableAttribute<Date>("createdAt")
    static let entityData = AlecrimCoreData.NullableAttribute<NSData>("entityData")
    static let entityType = AlecrimCoreData.NullableAttribute<String>("entityType")
    static let noDisturbing = AlecrimCoreData.NullableAttribute<Bool>("noDisturbing")
    static let recentChatDes = AlecrimCoreData.NullableAttribute<String>("recentChatDes")
    static let relatedID = AlecrimCoreData.NullableAttribute<Int32>("relatedID")
    static let unreadNum = AlecrimCoreData.NullableAttribute<Int32>("unreadNum")
    static let updatedAt = AlecrimCoreData.NullableAttribute<Date>("updatedAt")

}

// MARK: - AttributeType extensions


extension AlecrimCoreData.AttributeProtocol where Self.ValueType: RosterItem {
    var test: String { return "" }

    var alwaysOnTop: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("alwaysOnTop", self) }
    var createdAt: AlecrimCoreData.NullableAttribute<Date> { return AlecrimCoreData.NullableAttribute<Date>("createdAt", self) }
    var entityData: AlecrimCoreData.NullableAttribute<Data> { return AlecrimCoreData.NullableAttribute<Data>("entityData", self) }
    var entityType: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("entityType", self) }
    var noDisturbing: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("noDisturbing", self) }
    var recentChatDes: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("recentChatDes", self) }
    var relatedID: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("relatedID", self) }
    var unreadNum: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("unreadNum", self) }
    var updatedAt: AlecrimCoreData.NullableAttribute<Date> { return AlecrimCoreData.NullableAttribute<Date>("updatedAt", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var rosterItems: AlecrimCoreData.Table<RosterItem> { return AlecrimCoreData.Table<RosterItem>(dataContext: self) }

}

