//
//  Status.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - Status properties

extension Status {

    @NSManaged var carID: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var carInfo: String?
    @NSManaged var commentNum: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var content: String?
    @NSManaged var createdAt: Date?
    @NSManaged var fromFollow: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var fromHot: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var fromPerson: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var image: String?
    @NSManaged var likeNum: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var liked: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var loc: String?
    @NSManaged var mine: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var sent: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var thumbnail: String?
    
    @NSManaged var recentLikeUserName: String?

    @NSManaged var user: User?

}

// MARK: - Status query attributes

extension Status {

    static let carID = AlecrimCoreData.NullableAttribute<Int32>("carID")
    static let carInfo = AlecrimCoreData.NullableAttribute<String>("carInfo")
    static let commentNum = AlecrimCoreData.NullableAttribute<Int32>("commentNum")
    static let content = AlecrimCoreData.NullableAttribute<String>("content")
    static let createdAt = AlecrimCoreData.NullableAttribute<Date>("createdAt")
    static let fromFollow = AlecrimCoreData.NullableAttribute<Bool>("fromFollow")
    static let fromHot = AlecrimCoreData.NullableAttribute<Bool>("fromHot")
    static let fromPerson = AlecrimCoreData.NullableAttribute<Bool>("fromPerson")
    static let image = AlecrimCoreData.NullableAttribute<String>("image")
    static let likeNum = AlecrimCoreData.NullableAttribute<Int32>("likeNum")
    static let liked = AlecrimCoreData.NullableAttribute<Bool>("liked")
    static let loc = AlecrimCoreData.NullableAttribute<String>("loc")
    static let mine = AlecrimCoreData.NullableAttribute<Bool>("mine")
    static let sent = AlecrimCoreData.NullableAttribute<Bool>("sent")
    static let thumbnail = AlecrimCoreData.NullableAttribute<String>("thumbnail")
    static let recentLikeUserName = AlecrimCoreData.NullableAttribute<String>("recentLikeUserName")

    static let user = AlecrimCoreData.NullableAttribute<User>("user")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeProtocol where Self.ValueType: Status {

    var carID: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("carID", self) }
    var carInfo: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("carInfo", self) }
    var commentNum: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("commentNum", self) }
    var content: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("content", self) }
    var createdAt: AlecrimCoreData.NullableAttribute<Date> { return AlecrimCoreData.NullableAttribute<Date>("createdAt", self) }
    var fromFollow: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("fromFollow", self) }
    var fromHot: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("fromHot", self) }
    var fromPerson: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("fromPerson", self) }
    var image: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("image", self) }
    var likeNum: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("likeNum", self) }
    var liked: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("liked", self) }
    var loc: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("loc", self) }
    var mine: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("mine", self) }
    var sent: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("sent", self) }
    var thumbnail: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("thumbnail", self) }
    var recentLikeUserName: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("recentLikeUserName", self)}

    var user: AlecrimCoreData.NullableAttribute<User> { return AlecrimCoreData.NullableAttribute<User>("user", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var statuses: AlecrimCoreData.Table<Status> { return AlecrimCoreData.Table<Status>(dataContext: self) }

}

