//
//  ClubJoining.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - ClubJoining properties

extension ClubJoining {

    @NSManaged var alwaysOnTop: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var alwaysOnTopDate: NSDate?
    @NSManaged var clubID: String?
    @NSManaged var joinDate: NSDate?
    @NSManaged var nickName: String?
    @NSManaged var noDisturbing: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var showNickName: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var userID: String?

}

// MARK: - ClubJoining query attributes

extension ClubJoining {

    static let alwaysOnTop = AlecrimCoreData.NullableAttribute<Bool>("alwaysOnTop")
    static let alwaysOnTopDate = AlecrimCoreData.NullableAttribute<NSDate>("alwaysOnTopDate")
    static let clubID = AlecrimCoreData.NullableAttribute<String>("clubID")
    static let joinDate = AlecrimCoreData.NullableAttribute<NSDate>("joinDate")
    static let nickName = AlecrimCoreData.NullableAttribute<String>("nickName")
    static let noDisturbing = AlecrimCoreData.NullableAttribute<Bool>("noDisturbing")
    static let showNickName = AlecrimCoreData.NullableAttribute<Bool>("showNickName")
    static let userID = AlecrimCoreData.NullableAttribute<String>("userID")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: ClubJoining {

    var alwaysOnTop: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("alwaysOnTop", self) }
    var alwaysOnTopDate: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("alwaysOnTopDate", self) }
    var clubID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("clubID", self) }
    var joinDate: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("joinDate", self) }
    var nickName: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("nickName", self) }
    var noDisturbing: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("noDisturbing", self) }
    var showNickName: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("showNickName", self) }
    var userID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("userID", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var clubJoinings: AlecrimCoreData.Table<ClubJoining> { return AlecrimCoreData.Table<ClubJoining>(dataContext: self) }

}

