//
//  NSManagedObject.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - NSManagedObject properties

extension NSManagedObject {

    @NSManaged var atString: String?
    @NSManaged var commentID: String?
    @NSManaged var content: String?
    @NSManaged var createdAt: NSDate?
    @NSManaged var image: String?
    @NSManaged var sent: Bool // cannot mark as optional because Objective-C compatibility issues

    @NSManaged var activity: Activity?
    @NSManaged var responseTo: NSManagedObject?
    @NSManaged var user: User?

    @NSManaged var replies: Set<NSManagedObject>

}

// MARK: - NSManagedObject KVC compliant to-many accessors and helpers

extension NSManagedObject {

    @NSManaged private func addRepliesObject(object: NSManagedObject)
    @NSManaged private func removeRepliesObject(object: NSManagedObject)
    @NSManaged func addReplies(replies: Set<NSManagedObject>)
    @NSManaged func removeReplies(replies: Set<NSManagedObject>)

    func addReply(reply: NSManagedObject) { self.addRepliesObject(reply) }
    func removeReply(reply: NSManagedObject) { self.removeRepliesObject(reply) }

}

// MARK: - NSManagedObject query attributes

extension NSManagedObject {

    static let atString = AlecrimCoreData.NullableAttribute<String>("atString")
    static let commentID = AlecrimCoreData.NullableAttribute<String>("commentID")
    static let content = AlecrimCoreData.NullableAttribute<String>("content")
    static let createdAt = AlecrimCoreData.NullableAttribute<NSDate>("createdAt")
    static let image = AlecrimCoreData.NullableAttribute<String>("image")
    static let sent = AlecrimCoreData.NullableAttribute<Bool>("sent")

    static let activity = AlecrimCoreData.NullableAttribute<Activity>("activity")
    static let responseTo = AlecrimCoreData.NullableAttribute<NSManagedObject>("responseTo")
    static let user = AlecrimCoreData.NullableAttribute<User>("user")

    static let replies = AlecrimCoreData.Attribute<Set<NSManagedObject>>("replies")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: NSManagedObject {

    var atString: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("atString", self) }
    var commentID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("commentID", self) }
    var content: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("content", self) }
    var createdAt: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("createdAt", self) }
    var image: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("image", self) }
    var sent: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("sent", self) }

    var activity: AlecrimCoreData.NullableAttribute<Activity> { return AlecrimCoreData.NullableAttribute<Activity>("activity", self) }
    var responseTo: AlecrimCoreData.NullableAttribute<NSManagedObject> { return AlecrimCoreData.NullableAttribute<NSManagedObject>("responseTo", self) }
    var user: AlecrimCoreData.NullableAttribute<User> { return AlecrimCoreData.NullableAttribute<User>("user", self) }

    var replies: AlecrimCoreData.Attribute<Set<NSManagedObject>> { return AlecrimCoreData.Attribute<Set<NSManagedObject>>("replies", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var activityComments: AlecrimCoreData.Table<NSManagedObject> { return AlecrimCoreData.Table<NSManagedObject>(dataContext: self) }

}

