//
//  Status.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - Status properties

extension Status {

    @NSManaged var commentNum: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var content: String?
    @NSManaged var createdAt: NSDate?
    @NSManaged var image: String?
    @NSManaged var likeNum: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var location_des: String?
    @NSManaged var location_x: Double // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var location_y: Double // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var statusID: String?

    @NSManaged var car: SportCar?
    @NSManaged var user: User?

    @NSManaged var comments: Set<StatusComment>

}

// MARK: - Status KVC compliant to-many accessors and helpers

extension Status {

    @NSManaged private func addCommentsObject(object: StatusComment)
    @NSManaged private func removeCommentsObject(object: StatusComment)
    @NSManaged func addComments(comments: Set<StatusComment>)
    @NSManaged func removeComments(comments: Set<StatusComment>)

    func addComment(comment: StatusComment) { self.addCommentsObject(comment) }
    func removeComment(comment: StatusComment) { self.removeCommentsObject(comment) }

}

// MARK: - Status query attributes

extension Status {

    static let commentNum = AlecrimCoreData.NullableAttribute<Int32>("commentNum")
    static let content = AlecrimCoreData.NullableAttribute<String>("content")
    static let createdAt = AlecrimCoreData.NullableAttribute<NSDate>("createdAt")
    static let image = AlecrimCoreData.NullableAttribute<String>("image")
    static let likeNum = AlecrimCoreData.NullableAttribute<Int32>("likeNum")
    static let location_des = AlecrimCoreData.NullableAttribute<String>("location_des")
    static let location_x = AlecrimCoreData.NullableAttribute<Double>("location_x")
    static let location_y = AlecrimCoreData.NullableAttribute<Double>("location_y")
    static let statusID = AlecrimCoreData.NullableAttribute<String>("statusID")

    static let car = AlecrimCoreData.NullableAttribute<SportCar>("car")
    static let user = AlecrimCoreData.NullableAttribute<User>("user")

    static let comments = AlecrimCoreData.Attribute<Set<StatusComment>>("comments")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: Status {

    var commentNum: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("commentNum", self) }
    var content: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("content", self) }
    var createdAt: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("createdAt", self) }
    var image: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("image", self) }
    var likeNum: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("likeNum", self) }
    var location_des: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("location_des", self) }
    var location_x: AlecrimCoreData.NullableAttribute<Double> { return AlecrimCoreData.NullableAttribute<Double>("location_x", self) }
    var location_y: AlecrimCoreData.NullableAttribute<Double> { return AlecrimCoreData.NullableAttribute<Double>("location_y", self) }
    var statusID: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("statusID", self) }

    var car: AlecrimCoreData.NullableAttribute<SportCar> { return AlecrimCoreData.NullableAttribute<SportCar>("car", self) }
    var user: AlecrimCoreData.NullableAttribute<User> { return AlecrimCoreData.NullableAttribute<User>("user", self) }

    var comments: AlecrimCoreData.Attribute<Set<StatusComment>> { return AlecrimCoreData.Attribute<Set<StatusComment>>("comments", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var statuses: AlecrimCoreData.Table<Status> { return AlecrimCoreData.Table<Status>(dataContext: self) }

}

